### ISSUE TITLE
Edit gift recipient from edit subscription screen. 

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscriptions-gifting#101]
Documenting a potential feature idea so I don't forget. 

Allow admin to edit recipients from the edit subscription screen similar to how admin can change a subscription customer. (https://cloudup.com/ccXmyhrorOF)

**Comment by seb86** [comment]
Would this allow you to add more than recipient? e.g. Lets say I want to manually create a subscription that is gifted to 10 other people.

**Comment by james-allan** [comment]
@seb86 No it wouldn't. It would only allow you to change the current recipient.

I'm not even sure how a subscription gifted to 10 people would work? It would probably be fine with digital/virtual goods, however, it wouldn't work with physical products and managing a subscription with 10 people having access to suspension, cancel etc would be a nightmare.

What's the use case for having 10 recipients of the one subscription?

**Comment by seb86** [comment]
@james-allan The use case would be for digital memberships. A client is wanting it where one person who is managing can give memberships to as many recipents as they want. 10 was the amount he was hoping for at least.

**Comment by james-allan** [comment]
Sounds like you want is what some people refer to as seats. i.e making 1 purchase grants you x number of seats that you can freely distribute. SkyVerge have this [feature on their roadmap](https://docs.woocommerce.com/document/woocommerce-memberships-roadmap/#section-3) for the Memberships plugin.

**Comment by seb86** [comment]
OK Cool.

**Comment by james-allan** [comment]
This has now been added with #175
