### ISSUE TITLE
Memberships Integration

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscriptions-gifting#103]
**WCM Process for Granting Memberships:**
WCM grant memberships on the processing and completed order status  hooks using the core function [`grant_membership_access`](https://github.com/Prospress/woocommerce-memberships/blob/master/woocommerce-memberships.php#L466).

Here Memberships loops over every membership plan and gets the products in the order which grant access to the plan. [(`get_access_granting_purchased_product_ids`)](https://github.com/Prospress/woocommerce-memberships/blob/master/woocommerce-memberships.php#L556).

Inside `get_access_granting_purchased_product_id` memberships gets all the items which grant access and in the case that the order contains a subscription(s) it will return the subscription with the longest expiration date. 

WCM will then grant membership access using the product returned.

In a nutshell, Memberships will grant a membership to the purchaser for the best product in the order.

Overall there are 3 main concerns that need to be addressed with Memberships and Gifting Integration:
 1. Granting memberships to recipients rather than purchasers
 1. Multiple membership granting products in the one order granting multiple memberships to multiple users. (try saying that 10 times fast :stuck_out_tongue_closed_eyes:) 
 1. Linking the correct subscription to the membership.

-------------------

<h5 id="heading_1">Granting access to the recipient rather than the purchaser:</h5>
The most obvious thing but worth noting. Pretty self-explanatory.

<h5 id="heading-2">Multiple membership granting products in the one order:</h5>
By default when multiple subscription products which all grant membership to the same plan are purchased in the one order, WCM will determine what the best subscription is to grant the membership (used for membership expiration purposes) (see [`adjust_access_granting_product_id`](https://github.com/Prospress/woocommerce-memberships/blob/master/includes/integrations/class-wc-memberships-integration-subscriptions.php#L682)). Here subscriptions with the longest/furthest end date take priority. This process brings up  some complications for gifting integration, for example:

_Using the following products:_
````
Simple Product: Grants membership for 3 weeks
Expiring Membership Subscription: expires in 2 months
Full Membership Subscription: never expires
```

If for instance someone purchased all 3 products, Memberships would determine that the Full Membership Subscription product will grant the membership because it never expires and the membership will be active as long as the subscription is active. 

However what would occur if someone purchased all 3 products but this time purchased Expiring Membership Subscription for _recipient 1_ and Full Membership Subscription for _recipient 2_ and Simple Product for themselves. Memberships would still determine that the Full Membership Subscription is the best and grant the membership using that product. However, we need the best product per user, per order so that each user is granted the membership which has been purchased for them.

<h5 id="heading-3">Linking the subscription to the membership:</h5>
Finally, if the membership is granted using a subscription product. The membership will be tied/linked to the subscription through post meta (see [`save_subscription_data`](https://github.com/Prospress/woocommerce-memberships/blob/master/includes/integrations/class-wc-memberships-integration-subscriptions.php#L860)). Inside `save_subscription_data` the subscription id is worked out by getting the subscription which contains the product id (used to grant the membership) and has the parent order id matching the order being processed. However this doesn't translate over to gifting very well as you can purchase the same product multiple times in the same order but for different recipients all of which will create individual subscriptions. 

_For example an order like this:_
```
Line Item 1) Full Membership Subscription -> Recipient 1 -> Subscription id 123
Line Item 2) Full Membership Subscription -> Recipient 2 -> Subscription id 124
Line Item 3) Full Membership Subscription -> Recipient 3 -> Subscription id 125
```

In this case, all the memberships granted from this order will be tied to subscription 123 as it's the first one found which matches the description (subscription created from order x containing the Full Membership Subscription product ). This would mean if recipient 1 suspended their subscription all 3 recipients would have their memberships paused.

**Comment by EneHacheCe** [comment]
Hello! Thanks for creating this! Have you tested if the integration with Memberships still works in the last version of WP and WooCommerce? It stopped working after I updated. Ir creates the users, but not the membership.

**Comment by EneHacheCe** [comment]
Hello! Thanks for creating this! Have you tested if the integration with Memberships still works in the last version of WP and WooCommerce? It stopped working after I updated. Ir creates the users, but not the membership.

**Comment by thenbrent** [comment]
Hi @EneHacheCe sorry for the trouble. I've just moved this report to a new issue so we can keep track of it. You can view it here: https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/140
