### ISSUE TITLE
Recipient don’t get Subcribers Role 

### ISSUE THREAD

**Issue by sbangnielsen** [Prospress/woocommerce-subscriptions-gifting#153]
The recipient of a gifted subscriptions does not change role as described in settings for Woocommerce Subscriptions.

<img width="747" alt="skaermbillede 2016-06-01 kl 11 51 41" src="https://cloud.githubusercontent.com/assets/11867622/15705350/4083183e-27ef-11e6-912a-003daef6b8bf.png">

In our test the recipient of the subscribtion remains ’Customer’ in stead of being set as ’Subscriber’.

Is that intended behaviour?

It makes it difficult to implement content restrictions based upon roles/capabilities.
(If we use Woocommerce Membership it doesn’t matter that much)

**Comment by james-allan** [comment]
@sbangnielsen thanks for reporting this, we'll get that fixed up. 😄
