### ISSUE TITLE
Add filterable function to allow 3rd parties to specify if a product is giftable

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscriptions-gifting#155]
Requested in tweet: https://twitter.com/pixelyzed/status/758509611246903296 it would be handy to allow 3rd parties to filter whether a product is giftable.

Currently, there are a few conditions placed on whether the option to gift a product is displayed:

- On the single product page [`WCSG_Product::add_gifting_option_product()`](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/0e8c8ac5cd2b7a99addecf2188f58b0776dbf0d4/includes/class-wcsg-product.php#L65) _(is the product a subscription product and there isn't a request to switch)_
- On the cart and checkout pages [`WCSG_Cart::is_giftable_item()`](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/0e8c8ac5cd2b7a99addecf2188f58b0776dbf0d4/includes/class-wcsg-cart.php#L126-L128) _(is the product a subscription product and isn't a renewal or switch cart item)_

One of the initial questions I would have on implementing such a filter would be what level of that logic is filterable. Do we just allow 3rd parties to bypass the "is subscription product" check, all of those conditions or none of those conditions but introduce a new filterable condition that just defaults to `true` that allows third parties to return `false` instead? ¯\\_(ツ)_/¯

One of my concerns about allowing third parties to bypass all those checks (is subscription product, renewal or switch) is that those conditions are there because things just wouldn't work if gifting was enabled in those scenarios. 

Thoughts?

**Comment by javorszky** [comment]
Hm, what if we'd allow 3rd parties to do their checks first (is it a product that I want to be gifted?), but then leave these logic checks in place for whatever their filter ends up providing? In essence we'd be overwriting the result of their filters.

**Comment by thenbrent** [comment]
@james-allan I'd add a new function like `WCSG_Product::is_giftable(  $product  )` or `wcsg_is_product_giftable( $product )` which:

1 checks if `WC_Subscriptions_Product::is_subscription( $product )`
2. passes the return value through a filter for 3rd parties to use

Then replace the use of `WC_Subscriptions_Product::is_subscription()` [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/0e8c8ac5cd2b7a99addecf2188f58b0776dbf0d4/includes/class-wcsg-cart.php#L127), [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/0e8c8ac5cd2b7a99addecf2188f58b0776dbf0d4/includes/class-wcsg-product.php#L65) and anywhere else hardcoding to subscription products only with that new function.

That will continue to honour the conditions around gifting subscription renewals/switched etc., but make it possible for certain products to be flagged as giftable or not.

It will also make it easier to support gifting other product types in future, like non-subscription membership products (see #149) or to add an admin UI to specify which products are or aren't switchable, if need to add that later on.
