### ISSUE TITLE
Programmatically order subscription as a gift

### ISSUE THREAD

**Issue by sbangnielsen** [Prospress/woocommerce-subscriptions-gifting#157]
This is not issue, more like a question –  hope it’s okay

I‘ve seen examples floating around ([here](http://wordpress.stackexchange.com/questions/202873/woocommerce-how-to-use-wc-create-order-with-subscription-product) and [here](https://gist.github.com/vishalbasnet23/181f640053d5400530a4411a93cf87f7)) of how it is possible to order a subscription programmatically.

But I was wondering whether it was possible to programmatically create an order, where purchaser and recipient are two differents users, if the Woocommerce Subscriptions Gifting extension is installed?

**Comment by thenbrent** [comment]
Hi @sbangnielsen. What determines whether a subscription is gifted or not is simply a post meta entry with the key `_recipient_user` and the value of a user ID (e.g. `12`).

I'm pretty sure if you set that after creating the subscription with the code samples above, it will be treated as a gifted subscription consistently by the rest of the codebase.

For example:

```
$recipient_user_id = 12;
update_post_meta( $subscription_id, '_recipient_user', $recipient_user_id );
```

The `_customer_user` on the subscription should be set to the the purchaser.
