### ISSUE TITLE
Batch processing renewal payments

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#161]
Asked by @LukeAbell on https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/149#issuecomment-237977738: 

> One question I have, if a user purchases 30 gift subscriptions in one transaction, when the renewal time happens, will it charge their card 30 times, or just one batch charge? We'd like it to just charge the card in one lump sum.

**Comment by thenbrent** [comment]
@LukeAbell as each subscription purchased for a different recipient will create a separate subscription, that would mean 30 separate subscriptions are created and 30 separate renewal orders/payment will be created.

We built the underlying infrastructure into Subscriptions v2.0 to handle batch processing renewals. That means it is possible with some custom code to create one renewal order and one payment for `2...n` subscription renewals. Although the infrastructure is there, the code to batch them and we don't have plans to add it yet (we'd need to hear more demand for it before adding it to the roadmap, this is the first request I've seen so far).

**Comment by LukeAbell** [comment]
Thanks for the response @thenbrent! Myself and team can make the customizations. Any chance you could give us a head start in terms of where we need to add-on to the plugin to make this happen?

Thanks!

**Comment by thenbrent** [comment]
Sure, I can give you some pointers. It's not going to be easy, and these pointers probably won't be complete and may be missing things completely, but _hopefully_ they'll save some time figuring out how to do it.

First, your team will need some background on how Subscriptions processes renewal payments. I've just written up a brief developer's guide for that and you can find it here: https://gist.github.com/thenbrent/26ba2035745667301fbd3b4cc6d13fc1 (it will probably make sense to share with others in future so I've written it as a gist instead of in this comment).

As mentioned in that guide, the renewal order is created in `WC_Subscriptions_Manager::prepare_renewal()`, which is attached to `'woocommerce_scheduled_subscription_payment'` with a priority of `1`.

To batch/group renewals for multiple subscription then, the best approach is probably to:

1. attach a callback to `'woocommerce_scheduled_subscription_payment'` with a priority like `5` (this is greater than `1` so it runs after `WC_Subscriptions_Manager::prepare_renewal()` but less than `10` so it runs before `WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment()`)
1. in that callback, you'll want to find all other subscriptions relating to the customer scheduled to renewal around the same time
1. account for those by either increasing quantity of the line item or adding new line items to the last renewal order (found via `$subscription->get_last_order( 'all' )`) which will be the order generated in `WC_Subscriptions_Manager::prepare_renewal()`
1. make sure the renewal process for those other subscriptions does not run (this is the tricky part... it could be done by [reducing Action Scheduler's batch size to 1](https://github.com/prospress/action-scheduler#increasing-batch-size) or perhaps dynamically unhooking Subscriptions callbacks, like `WC_Subscriptions_Manager::prepare_renewal()` and `WC_Subscriptions_Payment_Gateways::gateway_scheduled_subscription_payment()` for subscriptions that have already been handled by your code)

As I said, it won't be easy, and will require a lot of testing to avoid serious issues (like duplicate payments). You can test renewals using the guide here: https://docs.woocommerce.com/document/testing-subscription-renewal-payments/

If you come up with something good, we'd love to release it publicly too and can offer code review/auditing in return for you being willing to do that.

**Comment by LukeAbell** [comment]
@thenbrent thank you! that is incredibly helpful! Do you think it would make more sense to try to incorporate just gifting memberships and not setting up subscriptions for each?

**Comment by thenbrent** [comment]
That depends on whether you want a future payment. If you don't need any renewal payments, like monthly or yearly fees to maintain the membership, you don't need to worry about using Subscriptions at all. If you need recurring payments, you also need Subscriptions.

**Comment by LukeAbell** [comment]
@thenbrent what if there was one subscription set up, and a line item for each membership?

**Comment by thenbrent** [comment]
@LukeAbell yep, that's the easiest way. Though I'm not sure how Memberships/Subscriptions/Gifting will handle that as you'd need to gift the memberships, but also have each membership associated with the same subscription, even though they are associated with different users. ¯\\_(ツ)_/¯

**Comment by thenbrent** [comment]
@LukeAbell I'm going to close this Issue now as I think I've answered the question and it sounds like you may need to approach it in a different way anyway. 😄
