### ISSUE TITLE
Allow recipient to choose product variants?

### ISSUE THREAD

**Issue by danomurray** [Prospress/woocommerce-subscriptions-gifting#162]
Hi,

Is it possible using this plugin to allow the gift recipient to choose product variants after the subscription has been set up as a gift?

I was imagining something like the recipient gets a link which allows them to login and customise the order before it is sent?

Thanks,

Dan.

**Comment by thenbrent** [comment]
Hi Dan,

No unfortunately that's not possible with the extension out-of-the-box. The recipient receives whichever product the purchaser selects for them. The recipient also can't [switch the subscription](https://github.com/Prospress/woocommerce-subscriptions-gifting#shared-subscription-management) either, which would be a way to allow them to change to a different variation at least.

I'll keep this open as a feature request so others folks can vote on it. If it gets a lot of support, we may add it in a future version (that probably won't be for more than a year at the soonest though).

If you need it sooner, you can work with a freelance developer to add that feature.

**Comment by danomurray** [comment]
Hi Brent,

Thanks for the plugin and the lightning-fast response! 

The use case is somewhat similar to your coffee subscription example except that the purchaser gets to create their own blend by selecting from lots of dimensions. It has been mentioned that it would be a nice-to-have if the gift could be paid for by the giver then personalised by the recipient.

We're developers so we'll take a look at the plugin anyway and make a call about trying to adapt it to achieve this!

Thanks again,

Dan.

**Comment by thenbrent** [comment]
> We're developers so we'll take a look at the plugin anyway and make a call about trying to adapt it to achieve this!

That makes it much easier.

Subscriptions are just a custom order type, so to change the product line item associated with a subscription you can:

1. delete the existing product (that was chosen by the purchaser at the time of checkout)
1. call [`WC_Abstract_Order::add_product()`](https://docs.woocommerce.com/wc-apidocs/class-WC_Abstract_Order.html#_add_product) on the subscription to add the new variation

For UI, you can use a pop-up on the [**My Account > View Subscription**](http://docs.woothemes.com/document/subscriptions/customers-view/) page to display the available attributes/variations and allow the customer to choose the blend for their subscription. You don't need to go through the whole [switching process](https://docs.woothemes.com/document/subscriptions/switching-guide/), we just have to use that more complex process to offer a generic solution for all payment gateways/products/stores use cases). This also doesn't have to be specific to gifted subscriptions if implemented that way. It can be used by anyone to customise the blend they receive at the next renewal.

**Comment by danomurray** [comment]
Great - thanks for the help, much appreciated!

Cheers,

Dan.
