### ISSUE TITLE
Call to a member function get_date() on boolean

### ISSUE THREAD

**Issue by benplum** [Prospress/woocommerce-subscriptions-gifting#165]
We're seeing a new error in this file:

includes/class-wcsg-memberships-integration.php in update_subscription_id at line 162:

```
wc_memberships()->get_subscriptions_integration()->update_related_membership_dates( $subscription, 'end', $subscription->get_date( 'end' ) );
```

**Comment by james-allan** [comment]
Hi @benplum, thanks for the report.

Have you been able to reliably replicate this error? If so, the steps to do so would be great. 

I wasn't able to replicate these errors locally but I have a suspicion of what is happening so I've pushed up a possible fix and submitted it for review.

At this point I can't give you a timeframe of when those changes will be reviewed and released as we are currently working on the next release of Subscriptions but you can track the progress of it here #166.
