### ISSUE TITLE
Recipient can manually pay for renewal order

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscriptions-gifting#176]
In the Gifting readme [(here specifically)](https://github.com/Prospress/woocommerce-subscriptions-gifting#purchaser-details-on-renewal-order), it states a recipient can pay for a failed or pending renewal order. The changes merged with https://github.com/Prospress/woocommerce-subscriptions/pull/1692 prevent this. 

Mentioned in https://github.com/Prospress/woocommerce-subscriptions/pull/1692#issue-181074824 (in the final dot point) it says that I initially planned to use `current_user_can( 'pay_for_order', $order_id )` which would allow Gifting to add a filter to allow recipients to pay renewal orders. However, because that `'pay_for_order'`capability check in the current version of WC allows all users to pay for orders (because of the strange situation where the [`empty( $order->id )`](https://github.com/woocommerce/woocommerce/blob/2.6.4/includes/wc-user-functions.php#L277) condition always returns true - _this has been fixed in the `master` branch of WC core_).

And so we find ourselves in a bit of a predicament from a Gifting point of view because the implementation I settled on in https://github.com/Prospress/woocommerce-subscriptions/pull/1692 (`get_current_user_id() !== $order->get_user_id()`) isn't very 3rd party dev friendly.

**Comment by rogercoathup** [comment]
@james-allan -- does it make sense for gifting to introduce a new capability `pay_for_renewal`, and use that?

**Comment by thenbrent** [comment]
We could possibly add a `pay_for_renewal_order` cap to Subscriptions.
