### ISSUE TITLE
Change the recipient of a gift?

### ISSUE THREAD

**Issue by benplum** [Prospress/woocommerce-subscriptions-gifting#177]
Is it possible to change the recipient of a gift? A purchase was accidentally attributed to the wrong user, and we are wondering if there is a way to change this for the purchaser.

**Comment by thenbrent** [comment]
Hi @benplum there will be an interface to do this once https://github.com/Prospress/woocommerce-subscriptions-gifting/pull/175 is merged. It's only possible by editing the database at present.

**Comment by benplum** [comment]
That's great! Can you share what needs to be edited in the database for the time being?

**Comment by james-allan** [comment]
> Can you share what needs to be edited in the database for the time being?

Sure. You'll need to add an entry into the post meta table using the `_recipient_user` post meta key with the value being the user id where the post id is the subscription's post id.

If you're doing it via code you can use something like: 

```
update_post_meta( $post_id, '_recipient_user', $user_id );
```

Through the normal checkout process, the recipient id is also added to order item meta but I don't believe you will lose any functionality if it's missing. If however you want to also add that you will need to use the `wcsg_recipient` order item meta key where the value is in the following format:
`'wcsg_recipient_id_' . $recipient_user_id` (eg `wcsg_recipient_id_4`) for each subscription order item.

**Comment by james-allan** [comment]
@benplum I'm going to close this one now that #175 has been merged. With the latest version, you can change the recipient from the edit subscription screen.
