### ISSUE TITLE
How to pack the sell of a suscription and a gift suscription at the same time?

### ISSUE THREAD

**Issue by JLMOINE** [Prospress/woocommerce-subscriptions-gifting#179]
Hi, I'd like to sell pack a suscription and a gift suscription (make a couple suscription) ?
1/ is it possible in your perception?, cause I'm having trouble with the multiple suscription woocommerce process.
2/ if yes how to acheive it ?
3/ is it possible to show the "is it a gift" field only on certain products ?

thanks

**Comment by james-allan** [comment]
Hi @JLMOINE 

I'm not quite sure i understand what you mean by: 

>  I'd like to sell pack a suscription and a gift suscription (make a couple suscription) ?

Are you wanting customers to be able to build a subscription pack/box and gift it? Sorry, could you elaborate further please. 

Regarding your 3rd question: 

> is it possible to show the "is it a gift" field only on certain products ?

Yes it is with custom code. 

The filter `wcsg_is_giftable_product` allows you remove the option for certain products. The snippet below will give you an example of how to use it: 

```php
function eg_is_giftable_product( $is_giftable, $product ) {
	$giftable_product_ids = array( 24, 12859, 11418 );

	return in_array( $product->id , $giftable_product_ids );
}
add_filter( 'wcsg_is_giftable_product', 'eg_is_giftable_product', 10, 2 );
```

That's a whitelist approach where all the products you want to display the "This is a gift" option should be included in the `$giftable_product_ids` array. All other products will not display the gift option.

**Comment by JLMOINE** [comment]
James, thanks for the tip, I'll give it a try.

> I'd like to sell pack a suscription and a gift suscription (make a couple suscription)

I'm trying to make a couple suscription, for exemple the husband will by a grouped suscription product of 2 suscriptions. the first one for himself and the secod one for his wife. therefore I need to able the gift suscription field on only the second suscription in order to make the husband enter his wife e-mail adress.


I've got another question that answer should help me a lot 

in the suscription page we are able to retrieve the customer (in my example the husband) on the gift suscription (the wife suscription)

Is it possible in anyway to attach the recipeint to the customer ? (have the wife info on the husband' suscription) ?

Thanks in advance

Jean-Louis
