### ISSUE TITLE
Recipient Cannot Get Past Account Details Form

### ISSUE THREAD

**Issue by goldhat** [Prospress/woocommerce-subscriptions-gifting#182]
Testing out the plugin I found no matter what is entered at my-account/new-recipient-account/ the form reloads with no errors visible. We can't confirm if it is a validation failure because no validation errors are shown. If we purposely skip required fields, again form reloads with no errors. If we try to enter information that would validate, form reloads with no errors shown. All paths lead to the form reloading. 

The form information, is not saved. The user has no navigation to leave the form, and if we manually change the url to try to reach /my-account it just redirects us back to my-account/new-recipient-account/.

We have a demo site where this was tested, it is running WCS Version 2.0.20 with v1.0 of gifting plugin:

http://wcs.goldhat.ca/my-account/new-recipient-account/
Username: contactfriend
Password: iw(ptuM!(UsR

That user was created by gifting plugin when a subscription order was place for them. Site is Twenty Sixteen, in case not showing validation errors is a theme issue.

**Comment by goldhat** [comment]
Further testing showed the form just wasn't validating (zip code error). The validation error don't show because in the template templates/new-recipient-account.php there is no wc_print_notices();. The validation routine uses wc_add_notice() so in order to show those notices to the user that templates needs <?php print wc_print_notices(); ?> at the top of it. And it works pretty good just adding that line at the top of the template, but probably should be wrapped in a div with a class name like "validation error". 

Perhaps there is an expectation that a WC theme would already have wc_print_notices() called in a another theme?

**Comment by goldhat** [comment]
Created pull request for this issue https://github.com/Prospress/woocommerce-subscriptions-gifting/pull/184

**Comment by james-allan** [comment]
Thanks @goldhat for debugging and submitting a PR for this. 😄 

I've had to resubmit your PR with a tiny change so it can be merged (#185). More info here https://github.com/Prospress/woocommerce-subscriptions-gifting/pull/184#issuecomment-260271441

**Comment by goldhat** [comment]
Glad to help, cheers.
