### ISSUE TITLE
Shipment costs

### ISSUE THREAD

**Issue by fox-didl** [Prospress/woocommerce-subscriptions-gifting#188]
In Europe we have different shipment costs to the countries. We are selling physical goods and not digital ones. We can send a package to germany with 5 euro and to france we have 10 euro. We ware working with the table rate shipping.

A gifted subscription contains fixed shipment costs. When the receiver of the gift change the germany address to france or spain, we will get a financal problem.

The same problem will be there with buying more than one gifted subscriptions. The shop-owner don't know the final shipments-costs - there is just the email address.

There should be a solution to handle this for shops with physical goods.

If not possible it should be able to eneble this feature on single product level.

**Comment by thenbrent** [comment]
This behavior isn't unique to gifted subscriptions. It's inherited from the Subscriptions core plugin.

To get the change address behavior changed in Subscriptions core, please request it here: http://ideas.woocommerce.com/forums/133476-woocommerce

If the request gets over 200 votes we will change it.

In the meantime, you can remove the _Change Address_ button if you do not wish customers to be able to change their addresses without the shipping costs being recalculated: https://docs.woocommerce.com/document/subscriptions/faq/#section-64
