### ISSUE TITLE
Hide pricing and other billing information on recipient facing pages/emails

### ISSUE THREAD

**Issue by fox-didl** [Prospress/woocommerce-subscriptions-gifting#189]
For the receiver of the gifted subscriptions it's not nice to see the price of the gifted product. In this case the receiver could get the feeling he/she has to pay this costs, because a other person added a subscription for him/her.

Is there a possibility to disable this price-information in emails and dashboard if the subscritption is a gifted subscription?

**Comment by thenbrent** [comment]
I'll leave this open as a feature request and if we see significant demand for it we will offer something to address it.

In the meantime, email templates can be customized to remove pricing if you would prefer that: https://docs.woocommerce.com/document/automated-follow-up-emails-docs/custom-email-templates/#section-3

**Comment by ledjay** [comment]
@thenbrent hi, I'm looking to customize the emails sent to the gifteR and gifteD customers using the  Follow-Ups plugin but I can't find a way to target just the person who offers the gift. If I use an order trigger the both receive the emails !
Is there any solution out there ?

**Comment by thenbrent** [comment]
@ledjay you would need to do it with code. Gifting and Follow-ups aren't integrated.

**Comment by rogercoathup** [comment]
+1 

Giving a gift; it's nice to hide the price from the recipient.  We've had a few complaints from gift givers that the price of their gift was revealed in the new recipient email.

Am overriding the recipient-new-intial-order email to avoid this.  It's not the easiest to override though just to strip the price, as it re-uses the shared email-order-items.php template

**Comment by james-allan** [comment]
I'm going to broaden the scope of this a little to include hiding prices and purchaser billing information. Some of the feedback we got from the WooCommerce team: 

> Can the purchaser’s billing information and the price of the subscription be hidden from the recipient? If this is purchased as a gift, I as a purchaser might want to hide that from the recipient.

At the moment prices and billing information is visible to the recipient in:
- [ ] **[Emails](https://github.com/Prospress/woocommerce-subscriptions-gifting#emails) sent to the recipient**
  - [ ] New order - sent after sign-up
  - [ ] Recipients also receive renewal emails which include prices and billing information
- [ ] **My Account** 
   - [ ] Subscriptions table (https://cloudup.com/cjVX5Z0L7tB _subscription 66 is a gift_) 
   - [ ] View Subscription subscription totals - https://cloudup.com/cNHWUHNX5gK
   - [ ] View Subscription related orders table - https://cloudup.com/cY2t9v9d1dc
   - [ ] Billing Address - https://cloudup.com/cIbZlo4qkGO

**Comment by LCmry** [comment]
@james-allan While recipients can't view parent orders, they can view renewal orders, and if they click on a related order from the view subscription page then it brings up the renewal order, complete with prices.  Should the recipient still be allowed to see these orders?  In the **My Account > Orders** table the orders do not appear, only in the **Related Orders** table on a view subscription page.

**Comment by james-allan** [comment]
Ah good point @LCmry. 

This [part of the doc](https://github.com/Prospress/woocommerce-subscriptions-gifting#purchaser-details-on-renewal-order) mentions that both recipients and purchases should be able to pay for failed or manual renewal orders and I think that should remain in place. That is unless we get feedback from customers to change that or have an option to turn that off. 

That would still be possible right even if we did prevent the recipient from viewing the actual order and so there's no need for them to have access to the order.
