### ISSUE TITLE
Country pulldown not working on new-recipient-account

### ISSUE THREAD

**Issue by johnmontfx** [Prospress/woocommerce-subscriptions-gifting#192]
The country pulldown does not seem to be working correctly on my-account/new-recipient-account page. The pulldown is not populated and "No Matches Found" is displayed. There are no js errors visible in Chrome's console log. It appears as though all the appropriate data for the pulldown is available in the html source as CDATA. I'm not technical enough to fully debug this more fully. 

I just downloaded the plugin today so I thought I'd report it. This is present in our live install as well as our development install.

I also reduced the dev install to have three plugins active and the default Twenty Fifteen theme and the problem still exists:

**Only plugins active:**
WooCommerce 2.6.8 
WooCommerce Subscriptions 2.1.0
WooCommerce Subscriptions Gifting 1.0

**Active Theme:**
Twenty Fifteen Theme

<img width="703" alt="screen shot 2016-12-06 at 9 58 42 am" src="https://cloud.githubusercontent.com/assets/5710872/20932557/a22a8fba-bb9a-11e6-80e4-64abcd77e542.png">

**Comment by james-allan** [comment]
Hi @johnmontfx 

Thanks for the report. Just to make sure what you are experiencing is similar to an issue which was reported a couple of weeks ago, does your store have shipping disabled? 

The issue (fixed with #181 - not yet released) was: 

> If you disable shipping from WC Settings (https://cloudup.com/cohPOMXyU7W), the shipping address fields are still displayed. On top of there being no reason to collect the recipient's shipping address in this scenario, this actually makes the form unsubmittable because the country is a required field but WC cannot populate the dropdown (https://cloudup.com/cVhtks_f9sU).

**Comment by johnmontfx** [comment]
Yep -- that's it. We don't enable shipping since we only provide memberships and digital download distribution.  The pull request seems as though it would work brilliant for us, including the filter

Sorry about that, as I looked only through the issues and not the pull requests.
