### ISSUE TITLE
Multiple Recipients

### ISSUE THREAD

**Issue by thollis78** [Prospress/woocommerce-subscriptions-gifting#194]
WC automatically groups like items - so one line item with a qty of 2.
but I can only add one email for the gift recipient. I need to either make them all line items OR add multiple emails for gift recipients.

**Comment by thenbrent** [comment]
>  need to either make them all line items

Yes, that's correct. Each gifted subscription product needs to be a separate line item. This ensures a separate subscription is created for each recipient/purchaser combination.

If you don't need to sell multiple quanties of the gifted item, the [_Sold Individually_ product option](https://docs.woocommerce.com/document/managing-products/#product-data) can make this clearer for customers.

**Comment by thollis78** [comment]
I'm selling corporate memberships (subscription based) where they have several individual (corporate associates) memberships (from 3-6). When they purchase the corporate membership, they have assoicate membership automatically added to their card (only 1) I'm not sure how to use Sold individually to make that happen.

**Comment by thenbrent** [comment]
@thollis78 nor am I. If you figure out a way to do it, please let us know how and we can add it to the [docs](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/master/README.md) to help others.
