### ISSUE TITLE
Woocommerce 3.0 bug

### ISSUE THREAD

**Issue by studioluminous** [Prospress/woocommerce-subscriptions-gifting#202]
When viewing recent orders in the account section I receive this error text viewing the gifted order in full: 
Warning: Declaration of WCSG_Email_Completed_Renewal_Order::trigger($order_id) should be compatible with WCS_Email_Completed_Renewal_Order::trigger($order_id, $order = NULL) in mysite.com/wp-content/plugins/woocommerce-subscriptions-gifting-master/includes/emails/class-wcsg-email-completed-renewal-order.php on line 63

Warning: Declaration of WCSG_Email_Processing_Renewal_Order::trigger($order_id) should be compatible with WCS_Email_Processing_Renewal_Order::trigger($order_id, $order = NULL) in mysite.com/wp-content/plugins/woocommerce-subscriptions-gifting-master/includes/emails/class-wcsg-email-processing-renewal-order.php on line 60

**Comment by ajgw** [comment]
I had this issue too and deactivated plugin because of this.

**Comment by thenbrent** [comment]
@studioluminous @ajgw I'm sorry, the whole team has been busy trying to get Subscriptions from working with 3.0 for the last couple of months, so we haven't been able to get to Gifting or our other free plugins to work with it properly yet. We will update Gifting to work with 3.0 eventually, but I can't provide an ETA on that yet.

For now, I've created #203 to keep track of that. You can subscribe to that Issue to be notifed once we get working on it.

For now, I would either keep Gifting disabled or not use WooCommerce 3.0 if possible. Sorry for the trouble. We strive to avoid these types of issues, but 3.0 placed an overwhelming burden on our team.
