### ISSUE TITLE
Fix Travis Integration

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#212]
It looks like there is a bug in the `tests/bin/travis.sh` file leading to the following fatal:

```
fatal: repository 'https://[secure]@github.com/Prospress/woocommerce-subscriptions.git/' not found
```

For a full example, see https://travis-ci.org/Prospress/woocommerce-subscriptions-gifting/jobs/260068487

**Comment by james-allan** [comment]
I have no idea what's so ever but I wonder if it has something to do with the `$GITHUB_TOKEN` ([here](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/fix_travis/tests/bin/travis.sh#L19))? I can't think of any other reason for why this would have broken all of a sudden.

**Comment by jconroy** [comment]
@james-allan I tried updating the token, still get the same thing

**Comment by jconroy** [comment]
> I tried updating the token, still get the same thing

I didn't have the permission set properly for private repos. Seens to be working ok.

Just for my future self reference. As I went back through a bunch of docs to see if things have changed

https://developer.github.com/v3/auth/ (this one has the different url formats for auth)
