### ISSUE TITLE
Translation to spanish?

### ISSUE THREAD

**Issue by icodemon** [Prospress/woocommerce-subscriptions-gifting#215]
Hello
very usefull plugin!
i want to do a translation of this to the spanish... how can i do it? 
i had translate it on a notepad and i want to upload in order to share with all the people and as an option of the plugin...

thanks for the info

Pablo

**Comment by thenbrent** [comment]
Hi @icodemon, Gifting uses WordPress i18n functions to make it possible to translate. You can lookup how to localise a WordPress plugin in general terms, and the instructions will allow you to also translate Gifting. For example:

* https://developer.wordpress.org/plugins/internationalization/localization/
* https://premium.wpmudev.org/blog/how-to-translate-a-wordpress-plugin/

Please note we did just have one fix for translation which we've just included with #219.
