### ISSUE TITLE
How to add gift recipients full name?

### ISSUE THREAD

**Issue by benjaminthedev** [Prospress/woocommerce-subscriptions-gifting#217]
Hi folks, 

Using this awesome plugin but I am having an issues.  When buying a gift how does the user add the name of the person?

I can not figure it out,

Help please.

Cheers

**Comment by benjaminthedev** [comment]
?

**Comment by james-allan** [comment]
The purchaser only needs to enter the recipient's email when making the initial purchase. If that email doesn't belong to an account which already exists on your site an account will be created for them and they will be prompted via email to enter their full name. More on that process here: https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/master/README.md#recipient-account-creation
