### ISSUE TITLE
Gift to multiple recipients at once

### ISSUE THREAD

**Issue by jorisberg** [Prospress/woocommerce-subscriptions-gifting#222]
Hi!
First of all, really love what you are doing here. Offers great functionality. I am running into one issue though.

I just cannot seem to manage to buy a subscription for multiple recipients. I have tried many things, such as this topic: https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/134 . Every time the product is replaced instead of added to the cart, when I try to add a new product.

But I just cannot get it to work. With some custom code from: https://stackoverflow.com/questions/32485152/woocommerce-treat-cart-items-separate-if-quantity-is-more-than-1 I managed to get the same product on multiple cart lines. However when proceeding to checkout, everything gets jammed into one line again.

Any way to fix this?

**Comment by jorisberg** [comment]
OK, turns out that a switch in the backend of the subscription settings was the issue.. Mixed checkout needs to be checked in order for this flow to work perfectly. Sorry for any inconvenience.

**Comment by thenbrent** [comment]
Thanks for letting us know you got is sorted @jorisberg. 👍
