### ISSUE TITLE
1 renewal order for n>1 subscriptions

### ISSUE THREAD

**Issue by jorisberg** [Prospress/woocommerce-subscriptions-gifting#223]
Hi guys,

Great work on this piece of code. Absolutely what I was looking for. I do stumble on one issue. We sell between 2 and 20 monthly subscriptions in one order. This means that if someone buys 20 subscriptions, this will be charged 20 separate times on their bank account each month. Not very convenient. It would be great if this could be aggregated into 1 order and 1 renewal payment (which gets updated when one of the 20 subscriptions is cancelled or if a subscription is added).

I saw that there has been a post on this about a year ago: https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/161

I was wondering if there are any developments in this area. Would be great :).

**Comment by thenbrent** [comment]
Hi @jorisberg thanks for the kind words, glad to hear it's helpful!

Unfortunately there are no developments yet on batch processing renewals. The brief spec I posted [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/161#issuecomment-238327002) is still mostly on-point, so it's still feasible to achieve with custom code. It's just not on our todo list as we have more [popular feature requests for Subscriptions](http://ideas.woocommerce.com/forums/133476-woocommerce/category/146472-extension-woocommerce-subscriptions) core that we need to prioritise.
