### ISSUE TITLE
Limit Gift capability by Product

### ISSUE THREAD

**Issue by mwisconsin** [Prospress/woocommerce-subscriptions-gifting#225]
Can the Gifting capability be limited by product?  I'd like only specific Products in the store to have the Gift prompt.  The documentation appears to qualify the gifting prompt to be store-wide.

**Comment by james-allan** [comment]
Hi @mwisconsin 

Yes, you can limit which products display the "Gift" prompt using the [`wcsg_is_giftable_product` filter](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/master/includes/class-wcsg-product.php#L86).

Something like this for example: 

```php
function eg_is_giftable_product( $is_giftable, $product ) {
    $giftable_product_ids = array( 24, 12859, 11418 );

    return in_array( wcsg_get_objects_id( $product ), $giftable_product_ids );
}
add_filter( 'wcsg_is_giftable_product', 'eg_is_giftable_product', 10, 2 );
```

will only display the gifting fields for products with IDs 24, 12859 and 11418. 

That example works as a white list, if you need a black list just replace the `return in_array( wcsg_get_objects_id( $product ), $giftable_product_ids );` with  `return ! in_array( wcsg_get_objects_id( $product ), $giftable_product_ids );` Let me know if you need further assistance with implementing this custom code. 

Keep in mind you'll need the most recent version of Gifting, which can download [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/archive/master.zip).
