### ISSUE TITLE
Errors in language (.pot) file

### ISSUE THREAD

**Issue by bernattorras** [Prospress/woocommerce-subscriptions-gifting#230]
## Ticket
https://secure.helpscout.net/conversation/458920912/2120/

## Description
Some errors appear when opening the languages/woocommerce-subscriptions-gifting.pot file in poEdit (or in translation plugins like LocoTranslate)

## Steps to replicate

1. Open poEdit
2. Click Archive>New Catalog from POT file and select languages/woocommerce-subscriptions-gifting.pot file

The following error appears:
![image](https://user-images.githubusercontent.com/1201868/32384478-4db1af32-c0bb-11e7-9ece-cd7ce41d08ad.png)

**Comment by thenbrent** [comment]
Fixed with #231.
