### ISSUE TITLE
Self-Gifting Allowed for Non-Customers

### ISSUE THREAD

**Issue by Shotster** [Prospress/woocommerce-subscriptions-gifting#234]
I'm not sure how, but a user was able to enter "Firstname Lastname (user@domain.com)" as the gift recipient's email address and successfully check out. When I try that on either the product detail page or the checkout page, I get an "Invalid email address" error.

I became aware of the issue because, while the order was processed just fine, a back-office system using a webhook (and assuming a valid email) threw an error. Not sure if the issue is with WCSG, but I don't know how else invalid data could have been entered.

I'm sorry I am unable to reproduce the issue, but if you have insights as to how this could've happened, I'd love to hear. I'm stumped. 😕

**Comment by Shotster** [comment]
Oi! I just figure it out! They simply entered their own email address. It's "the system" (presumably WCSG) that adds the first and last name and parentheses. Shouldn't it, instead, check that the recipient address is different from the billing address?

**Comment by james-allan** [comment]
@Shotster 

> It's "the system" (presumably WCSG) that adds the first and last name and parentheses.

Yes that's correct, when displaying the recipient we add the customer's first and last name if it exists. 

So you could see any number of these examples depending on whether the recipient has an account: 

- Firstname Lastname (user@domain.com)
- Firstname (user@domain.com)
- user@domain.com

If you just want the recipient's email address you'll need to get the recipient user ID (`WCS_Gifting::get_recipient_user( $subscription )`) and then get the email associated with that user.

> Shouldn't it, instead, check that the recipient address is different from the billing address?

We do prevent customers from entering their own email address as the recipient email, however, we only check the customer's user email, not the billing email - customers can have 2 emails associated with their account. 

I can't think off the top of my head why we only check the user email and not the billing email. For that reason, I'll mark this as a bug. Thanks for the report @Shotster

**Comment by Shotster** [comment]
Thanks for the prompt response, @james-allan.

> If you just want the recipient's email address you'll need to get the recipient user ID (WCS_Gifting::get_recipient_user( $subscription )) and then get the email associated with that user.

I'm using the JSON payload provided by the **order.created** webhook, and all I have is the **wcsg_recipient** meta field. IOW, the recipient's user ID is not available in the payload data. It would be impractical to do a lookup. (The hook endpoint isn't on the same server and does not use PHP.)

I had assumed, based upon all orders until this one, that the meta field contained only the email address. It would be far more efficient - assuming the meta field always contains _at least_ the email address - for me to simply extract it via regex.

Anyway, at least now I understand that the meta field does not contain what the site visitor is forced to enter on the front end.

Thanks for considering checking the recipient against the billing email. It might save someone else some troubleshooting time down the road.

🙂

**Comment by james-allan** [comment]
> I'm using the JSON payload provided by the order.created webhook, and all I have is the wcsg_recipient meta field. IOW, the recipient's user ID is not available in the payload data. It would be impractical to do a lookup. (The hook endpoint isn't on the same server and does not use PHP.)

Ah ok, thanks for the clarification.

I've just setup a webhook on my local site using the `order.created` topic and the only reference I found to the recipient is the `wcsg_recipient` line item meta key which has values like: `wcsg_recipient_id_137`. Is that the meta field you're referring to? 

In your initial description, you said the "Firstname Lastname (user@domain.com)" value is what was causing an error. How were you getting that value? I'm not receiving those values in my payload.

**Comment by Shotster** [comment]
I updated the title to better reflect the nature of the issue.

**Comment by Shotster** [comment]
> In your initial description, you said the "Firstname Lastname (user@domain.com)" value is what was causing an error. How were you getting that value? I'm not receiving those values in my payload.

Following is the **line_items** array in the JSON payload. If the buyer gifts to another email address, then just the recipient's email address appears as the value of the **wcsg_recipient** key. If they gift to themselves (i.e. the recipient email matches the billing email), then the value is the name with email in parentheses as shown below.

```
  "line_items": [
    {
      "id": 402,
      "name": "Membership - Annual",
      "sku": "membership",
      "product_id": 2111,
      "variation_id": 2114,
      "quantity": 1,
      "tax_class": "",
      "price": "100.00",
      "subtotal": "100.00",
      "subtotal_tax": "0.00",
      "total": "100.00",
      "total_tax": "0.00",
      "taxes": [],
      "meta": [
        {
          "key": "pa_billing-period",
          "label": "Billing Period",
          "value": "Annual"
        },
        {
          "key": "wcsg_recipient",
          "label": "Recipient",
          "value": "First Last (user@domain.com)"
        }
      ]
    }
  ],
```

WC Version 3.2.5
WCS Version 2.2.15
WCSG Version 1.0

**Comment by Shotster** [comment]
Oops! It's the **subscription.created** webhook - not **order.created**! (Sorry about that!)

**Comment by james-allan** [comment]
> Oops! It's the subscription.created webhook - not order.created! (Sorry about that!)

Ah okay, that makes sense. I've been able to replicate it now.

At first glance, I'm not really sure why the **subscription.created** and **order.created** webhooks are producing different line item meta values. 

For example:

**order.created** line items:

```
   "line_items":[  
      {  
         "id":31905,
         "name":"Weekly",
         "product_id":14628,
         "variation_id":0,
         "quantity":1,
         "tax_class":"",
         "subtotal":"24.95",
         "subtotal_tax":"0.00",
         "total":"24.95",
         "total_tax":"0.00",
         "taxes":[  

         ],
         "meta_data":[  
            {  
               "id":215291,
               "key":"wcsg_recipient",
               "value":"wcsg_recipient_id_137"
            }
         ],
         "sku":"",
         "price":24.95
      }
   ],
```

**subscription.created** line items:

```
"line_items":[  
      {  
         "id":31896,
         "name":"Weekly",
         "sku":"",
         "product_id":14628,
         "variation_id":0,
         "quantity":1,
         "tax_class":"",
         "price":"24.95",
         "subtotal":"24.95",
         "subtotal_tax":"0.00",
         "total":"24.95",
         "total_tax":"0.00",
         "taxes":[  

         ],
         "meta":[  
            {  
               "key":"wcsg_recipient",
               "label":"Recipient",
               "value":"user@example.com"
            }
         ]
      }
   ],
```

Both order line items and subscription line items should have the raw value which looks like the value I mentioned before `wcsg_recipient_id_137`. So I think it might actually be a bug that the "First Last (user@domain.com)" values are being sent in the subscription created payload to begin with. Also notice that subscriptions are sending the `meta` and orders are `meta-data` values. I suspect that's why there's a discrepancy. 

I understand `wcsg_recipient_id_137` isn't useful to you though since you can't do anything with user ID 137. To address that WCSG should probably be added some extra data into the payload though so you can get recipient related information.

**Comment by Shotster** [comment]
Thanks for looking into it. All I can say is that my back office system relies on having access to the recipient email when a subscription is created. That’s the information the buyer enters when they gift a subscription, so it makes sense that it would be accessible in the **subscription.created** web hook. If the meta data I’m using now is a bug, it’d be great if another meta field was provided containing the email address.
