### ISSUE TITLE
Plugin can not see WC Subscription plugin.

### ISSUE THREAD

**Issue by thirdfloorflat** [Prospress/woocommerce-subscriptions-gifting#235]
Subscription gifting plugin can not see WC Subscription plugin. Says that it is not installed and asking for the instalation of WC Subscriptiom plugin althou one is installed and activated.

WC version: 3.2.5
WC Subscriptions version: 2.2.13
WordPress version: 4.9.1

![zrzut ekranu 2017-12-02 o 13 20 20](https://user-images.githubusercontent.com/19794550/33515446-f060ff94-d763-11e7-9896-10739767d3c0.png)

![zrzut ekranu 2017-12-02 o 13 20 04](https://user-images.githubusercontent.com/19794550/33515443-e1b3fc94-d763-11e7-9e14-a5b5cf4dfbd8.png)

**Comment by rogercoathup** [comment]
Have you checked your folder name for the subs plugin, see also https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/178

**Comment by thirdfloorflat** [comment]
Just before you wrote that. :) Sorry for the duplicated post. Changed the names of both folders and everything works great. Thankx.
