### ISSUE TITLE
New translations not reflected on website.

### ISSUE THREAD

**Issue by thirdfloorflat** [Prospress/woocommerce-subscriptions-gifting#236]
I am translating this plugin (have both po i mo files in languages folder) but translations are not reflected on the website.

**Comment by thirdfloorflat** [comment]
Any thoughts?

**Comment by james-allan** [comment]
@thirdfloorflat translations should definitely work. I've just done a quick translation test using the Loco Translate plugin and they are loading fine. 

A couple of things to double check: 

1. Make sure you have set the site's language in **Dashboard > Settings > General** and that it matches the language ISO code used in the po and mo file names. For example https://cloudup.com/cRy8NcYtfxv
2. Make sure the mo and po files are in the `/wp-content/languages/plugins` folder
3. If you've placed the files inside the plugin directory (`wp-content/plugins/woocommerce-subscriptions-gifting/languages`) which isn't recommended (it will be overwritten by plugin updates) you'll need to move them over to `/wp-content/languages/plugins`. WCSG doesn't supports files inside that directory.
4. Finally, make sure your files are formatted correctly. 

Also take a look at this WooCommerce doc on how to translate WooCommerce:  https://docs.woocommerce.com/document/woocommerce-localization/. It's written specifically for translating WooCommerce so some things don't apply to WCSG but it's a fairly good reference.
