### ISSUE TITLE
Working with Ultimate Member roles?

### ISSUE THREAD

**Issue by Garconis** [Prospress/woocommerce-subscriptions-gifting#241]
Ultimate Member has a WooCommerce add-on that can change a user's role based on what product they purchased: [![Screenshot from Gyazo](https://gyazo.com/1c503bff0a44547f14d8f482d815c7e9/raw)](https://gyazo.com/1c503bff0a44547f14d8f482d815c7e9)

If the buyer gifts the subscription to another user... which user will get the new role? The purchaser or the recipient?

**Comment by thenbrent** [comment]
> which user will get the new role? The purchaser or the recipient?

Hi @Garconis, I'm not sure, I've never heard of Ultimate Member. Give it a test and let us know. We make sure we support WooCommerce Memberships, and we may add compatibility for other memberships plugins if demand proves popular enough. 🙂

**Comment by Garconis** [comment]
Unfortunately it doesn't seem to play well with their settings. When the subscription is purchased, it changes the BUYER's role. When ideally it would end up changing the RECIPIENT's role. I think part of the issue is that Ultimate Member is likely checking to see who the "Customer" is. And your plugin doesn't really set the RECIPIENT to be the Customer.
