### ISSUE TITLE
Adding compatibility for another subscription plugins

### ISSUE THREAD

**Issue by danicasati** [Prospress/woocommerce-subscriptions-gifting#243]
Hi.
Great plugin here.
It would be possible to add compatibility with another subscriptions plugins, like this one:
https://codecanyon.net/item/woocommerce-membership/8746370

**Comment by james-allan** [comment]
Hi @danicasati 

At the moment we only support [WooCommerce Memberships](https://woocommerce.com/products/woocommerce-memberships/), we may add compatibility for other memberships plugins like WooCommerce Membership if demand proves popular enough. 🙂
