### ISSUE TITLE
Shipping Address Not on Child Order After Renewal

### ISSUE THREAD

**Issue by mhennessie** [Prospress/woocommerce-subscriptions-gifting#246]
We are having an issue where the shipping address is not on the child order that is created when the subscription renews. This is causing a problem because ShipStation is pulling orders without addresses so labels cannot be created properly.

**Comment by james-allan** [comment]
@mhennessie Thanks for the report. 

What I believe is probably happening is that the subscription is renewing before the recipient has logged in and confirmed their account and entered their shipping details. 

When a subscription is purchased for a recipient who hasn't got an account, the subscription will be created with a blank shipping address. Once the recipient logs in and enters a new password, they will also be prompted to enter their shipping address. Once they do that, the subscription should be updated with their shipping address and all future renewal orders should then include those details. 

It sounds like in your case the recipient hasn't completed that step yet and when the renewal order was created, it copied a blank shipping address from the subscription. 

Could you confirm that's what has happened here?

**Comment by mhennessie** [comment]
@james-allan That does appear to be the issue. Is it possible to have the shipping address automatically copied from the initial order into the recipients profile?

**Comment by mhennessie** [comment]
This can be closed as a duplicate for issue #208
